import Link from 'next/link';
import { ArrowDown, ArrowUpRight, Check, Clapperboard, Code2, Palette, Sparkles, Radio, MoveRight } from 'lucide-react';
import { EnquiryForm } from './enquiry-form';
import Experience from './experience';
import { digitalServices, cinemaServices, channels, type PageInfo } from './site-content';

const icons=[Radio,Palette,Code2,Clapperboard];
export function DetailPage({page}:{page:PageInfo}){
 const cinema=page.division==='entertainment';const prefix=cinema?'/entertainment':'/it';const services=cinema?cinemaServices:digitalServices;const titleStart=page.title.slice(0,page.title.length-page.accent.length);const form= ['contact','careers','casting','investors'].includes(page.type);
 return <main id="main-content" className={`detail-page ${cinema?'cinema-theme':'digital-theme'}`}>
   {page.type==='division'&&cinema ? <Experience entertainment/> : <section className={`detail-hero ${page.type==='division'?'division-hero':''}`}>
    <img className="detail-art" src="/media/portal.jpg" alt="" aria-hidden="true"/>
    <div className="detail-hero-shade"/>
    <div className="detail-hero-content"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">ProDyum</Link><span>/</span>{page.division==='brand'?<span>{page.type==='about'?'About':'Contact'}</span>:<Link href={prefix}>{cinema?'Entertainments':'IT'}</Link>}{page.type!=='division'&&page.division!=='brand'&&<><span>/</span><span>{page.type==='contact'?'Contact':page.type==='portfolio'?'Projects':page.type==='casting'?'Cast & crew':page.type==='investors'?'Partnerships':page.type[0].toUpperCase()+page.type.slice(1)}</span></>}</nav><p className="eyebrow"><span className="status-dot"/>{page.eyebrow}</p><h1>{titleStart}<em>{page.accent}</em></h1><p className="detail-intro">{page.description}</p><div className="detail-hero-actions"><a className="primary-link" href="#page-content">{form?(page.type==='careers'||page.type==='casting'?'Introduce yourself':'Start a conversation'):page.type==='division'?'Explore our capabilities':'Explore this page'} <ArrowDown size={17}/></a>{page.type==='division'&&<Link className="text-action" href={`${prefix}/${cinema?'projects':'portfolio'}`}>{cinema?'Explore our channels':'Discuss your project'} <ArrowUpRight size={17}/></Link>}</div></div><div className="division-stamp" aria-hidden="true"><span>{cinema?'THE ART OF STORYTELLING':'THE SCIENCE OF POSSIBILITY'}</span><strong>{cinema?'02':'01'}</strong></div>
   </section>}
   <div id="page-content">
   {page.type==='division'&&<><section className="detail-section"><div className="section-heading"><div><p className="eyebrow">CONNECTED CAPABILITIES</p><h2>{cinema?'One story. Every stage.':'From strategy to the screen.'}</h2></div><Link className="text-action" href={`${prefix}/services`}>All services <ArrowUpRight size={18}/></Link></div><div className="capability-grid">{services.map((service,index)=>{const Icon=icons[index];return <Link href={`${prefix}/services#service-${index+1}`} className="capability-card" key={service.title}><div className="capability-top"><Icon size={27} strokeWidth={1.25}/><span>0{index+1}</span></div><h3>{service.title}</h3><p>{service.description}</p><span className="card-link">Explore <ArrowUpRight size={17}/></span></Link>})}</div></section>{cinema?<ChannelSection/>:<section className="industry-section detail-section"><p className="eyebrow">BUILT AROUND YOUR WORLD</p><h2>Different industries.<br/>Individual ambitions.</h2><div className="industry-list">{['Real estate','Education & training','Startups & small businesses','E-commerce brands','Entertainment & media','Local businesses'].map((name,i)=><div key={name}><span>0{i+1}</span><h3>{name}</h3><MoveRight size={18}/></div>)}</div></section>}<Process cinema={cinema}/><CrossWorld cinema={cinema}/></>}
   {page.type==='services'&&<><section className="detail-section service-list">{services.map((service,index)=>{const Icon=icons[index];return <article id={`service-${index+1}`} key={service.title} className="service-row"><span className="service-number">{service.number}</span><div className="service-body"><Icon size={30} strokeWidth={1.2}/><h2>{service.title}</h2><p>{service.description}</p><Link className="text-action" href={`${prefix}/contact`}>Discuss this service <ArrowUpRight size={17}/></Link></div><ul>{service.items.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul></article>})}</section><Process cinema={cinema}/><CallToAction href={`${prefix}/contact`} title={cinema?'Have a story in mind?':'What does your business need next?'}/></>}
   {page.type==='about'&&<><section className="detail-section story-section"><p className="eyebrow">OUR PERSPECTIVE</p><h2>Good work begins<br/>with <em>understanding.</em></h2><div className="story-copy"><p>{page.division==='brand'?'ProDyum brings together digital technology, marketing, and entertainment. Our two divisions share a belief in the power of considered ideas, thoughtful execution, and clear communication.':'ProDyum IT Pvt Ltd is a Hyderabad-based digital solutions company focused on helping businesses grow through technology, creativity, and strategic digital marketing.'}</p><p>{page.division==='brand'?'ProDyum IT helps businesses create a stronger digital presence. ProDyum Entertainments brings stories to the screen through production and post-production.':'We work with businesses to understand their goals, develop an approach, and bring it to life through design, marketing, websites, and multimedia.'}</p><Link className="text-action" href="/contact">Meet your next creative partner <ArrowUpRight size={18}/></Link></div></section><div className="values-grid detail-section">{[['Listen first','Understand the ambition, the audience, and the challenge before choosing the approach.'],['Think together','Bring different creative and technical perspectives into the same conversation.'],['Make it matter','Give every decision a purpose, from the first plan to the final detail.']].map(([title,description],i)=><article key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div><CrossWorld cinema={false}/></>}
   {page.type==='portfolio'&&<><section className="detail-section"><div className="section-heading"><div><p className="eyebrow">PROJECT DIRECTIONS</p><h2>What would you like to create?</h2></div></div><p className="section-note">These are project types we can discuss with you. For examples of completed client work, request relevant samples from our team.</p><div className="project-directions">{[['Brand identity','A new visual identity or a thoughtful refresh of your existing brand.','Strategy · Logo · Visual system'],['Business website','A website that tells your story and helps visitors take the next step.','UI/UX · Development · Responsive design'],['Digital campaign','A connected approach to content, social channels, and paid promotion.','Content · Social media · Advertising'],['Product & brand film','Visual content built around your product, business, or campaign.','Shooting · Editing · Reels']].map(([title,description,tags],i)=><Link key={title} href="/it/contact" className="project-direction"><span className="project-index">0{i+1}</span><div><p className="eyebrow">{tags}</p><h3>{title}</h3><p>{description}</p></div><ArrowUpRight size={28}/></Link>)}</div></section><CallToAction href="/it/contact" title="Ask for work that’s relevant to you."/></>}
   {page.type==='projects'&&<><ChannelSection/><section className="detail-section production-note"><Sparkles size={30}/><div><h2>A new story starts with an idea.</h2><p>Talk to us about movies, series, short films, music videos, or post-production for your next project.</p></div><Link className="primary-link" href="/entertainment/contact">Talk to the studio <ArrowUpRight size={17}/></Link></section></>}
   {page.type==='investors'&&<><section className="detail-section"><p className="eyebrow">A CONSIDERED CONVERSATION</p><h2>Bring the right questions<br/>to the table.</h2><div className="values-grid inline-values">{[['The project','Discuss the story, format, intended audience, and production scope.'],['The plan','Request a project-specific budget, schedule, and milestone outline.'],['The partnership','Explore responsibilities, reporting, distribution, and proposed terms with the team.']].map(([title,description],i)=><article key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><ContactSection kind="partnership" division="entertainment"/></>}
   {(page.type==='careers'||page.type==='casting')&&<><section className="talent-intro detail-section"><div><p className="eyebrow">YOUR CRAFT. YOUR PERSPECTIVE.</p><h2>{page.type==='casting'?'Behind the camera.\nIn front of it.':'Creative minds.\nCurious builders.'}</h2></div><div><p>{page.type==='casting'?'Share your discipline, experience, location, availability, and a portfolio or showreel link.':'Share your area of interest, experience, and a portfolio or CV link. Tell us about the kind of work you would like to do.'}</p><p className="section-note">This is an expression of interest. Specific openings, requirements, and next steps can be confirmed with the team.</p></div></section><ContactSection kind={page.type==='casting'?'casting':'career'} division={page.division}/></>}
   {page.type==='contact'&&<ContactSection division={page.division}/>}
   </div>
 </main>
}
function ChannelSection(){return <section className="detail-section channels-section"><div className="section-heading"><div><p className="eyebrow">WATCH. DISCOVER. CONNECT.</p><h2>Our channels.</h2></div><span className="section-note">Explore on YouTube <ArrowUpRight size={15}/></span></div><div className="channel-grid">{channels.map((channel,index)=><a className={`channel-card channel-${index}`} href={channel.url} key={channel.name} target="_blank" rel="noopener noreferrer"><div className="channel-cover"><span>{channel.mark}</span><div className="channel-play"><ArrowUpRight size={28}/></div></div><p className="eyebrow">{channel.tag}</p><h3>{channel.name}</h3><p>{channel.description}</p><span className="card-link">Visit channel <ArrowUpRight size={16}/></span></a>)}</div></section>}
function Process({cinema}:{cinema:boolean}){const steps=cinema?[['Develop','Define the story, format, and creative direction.'],['Plan','Bring the production scope, people, and schedule together.'],['Produce','Create the footage and performances that tell the story.'],['Finish','Shape the final film through edit, colour, VFX, and sound.']]:[['Understand','Start with your business, audience, and ambitions.'],['Plan','Create a clear approach to strategy and delivery.'],['Create','Bring the idea to life through design and technology.'],['Deliver','Review the details and bring the work into the world.']];return <section className="detail-section process-section"><p className="eyebrow">HOW IT COMES TOGETHER</p><h2>From possibility<br/>to <em>something real.</em></h2><div className="process-grid">{steps.map(([title,description],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>}
function CrossWorld({cinema}:{cinema:boolean}){return <section className="cross-world detail-section"><div><p className="eyebrow">ONE CONNECTED ECOSYSTEM</p><h2>{cinema?'A story can build a brand.':'A brand can tell a story.'}</h2><p>{cinema?'Explore the strategy, design, marketing, and technology of ProDyum IT.':'Discover the production and storytelling world of ProDyum Entertainments.'}</p></div><Link className="primary-link" href={cinema?'/it':'/entertainment'}>{cinema?'Explore Digital':'Explore Entertainment'} <ArrowUpRight size={18}/></Link></section>}
function CallToAction({href,title}:{href:string;title:string}){return <section className="detail-section page-cta"><p className="eyebrow">LET’S TALK POSSIBILITIES</p><h2>{title}</h2><Link className="primary-link" href={href}>Start a conversation <ArrowUpRight size={18}/></Link></section>}
function ContactSection({division,kind='project'}:{division:string;kind?:'project'|'career'|'casting'|'partnership'}){return <section className="detail-section contact-layout"><aside><p className="eyebrow">THE CONVERSATION STARTS HERE</p><h2>Say hello.</h2><a className="contact-email" href="mailto:hr@prodyum.in">hr@prodyum.in <ArrowUpRight size={19}/></a><div className="contact-location"><p className="eyebrow">FIND OUR WORLD</p><p>Hyderabad<br/>Telangana, India</p></div><div className="contact-location"><p className="eyebrow">LOOKING FOR SOMETHING ELSE?</p><Link href="/it/careers">Careers <ArrowUpRight size={15}/></Link><Link href="/entertainment/casting">Casting & crew <ArrowUpRight size={15}/></Link><Link href="/entertainment/investors">Partnerships <ArrowUpRight size={15}/></Link></div></aside><EnquiryForm kind={kind} division={division}/></section>}
