'use client';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Check, Copy, Mail } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';

export function EnquiryForm({kind='project',division='brand'}:{kind?:'project'|'career'|'casting'|'partnership';division?:string}){
 const [draft,setDraft]=useState<{body:string;href:string}|null>(null);const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
 const isTalent=kind==='career'||kind==='casting';
 const options=kind==='career'?['Digital marketing','Branding & design','Web development','Video & multimedia','Other']:kind==='casting'?['Actor / performer','Director / writer','Camera & lighting','Editing / colour / VFX','Sound / music','Production crew','Other']:kind==='partnership'?['Project collaboration','Production partnership','Investment enquiry','Distribution conversation','Other']:division==='it'?['Digital marketing','Branding & design','Web development','Video & multimedia','A combination of services']:division==='entertainment'?['Film production','Web series','Short film / music video','Post-production','Other']:['ProDyum IT — digital services','ProDyum Entertainments — production','A project across both divisions','Not sure yet'];
 function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const subject=`ProDyum ${kind==='project'?'project enquiry':kind==='career'?'career introduction':kind==='casting'?'casting & crew introduction':'partnership enquiry'} — ${data.get('interest')}`;const body=`Hello ProDyum team,\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\n${isTalent?'Location':'Company / organisation'}: ${data.get('company')||'Not provided'}\nInterest: ${data.get('interest')}\n${isTalent?'Portfolio / showreel':'Website / project reference'}: ${data.get('reference')||'Not provided'}\n\n${data.get('brief')}\n\nThank you,\n${data.get('name')}`;setDraft({body,href:`mailto:hr@prodyum.in?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});setCopied(false);setCopyError(false);}
 return <div className="enquiry-panel"><div className="form-intro"><span className="eyebrow">{isTalent?'INTRODUCE YOURSELF':'TELL US A LITTLE MORE'}</span><h2>{isTalent?'Let your work do the talking.':'Great work starts with a conversation.'}</h2><p>This form prepares an email to hr@prodyum.in. Review it, then send it from your email app.</p></div><form onSubmit={prepare} onChange={() => setDraft(null)} className="enquiry-form"><div className="form-grid"><label htmlFor="enquiry-name">Your name <span>*</span><Input id="enquiry-name" name="name" autoComplete="name" required maxLength={100} placeholder="Name"/></label><label htmlFor="enquiry-email">Email address <span>*</span><Input id="enquiry-email" name="email" type="email" autoComplete="email" required maxLength={150} placeholder="you@example.com"/></label><label htmlFor="enquiry-company">{isTalent?'Your location':'Company / organisation'}<Input id="enquiry-company" name="company" autoComplete={isTalent?'address-level2':'organization'} maxLength={150} placeholder={isTalent?'City':'Company name'}/></label><label htmlFor="enquiry-interest">{isTalent?'Your discipline':'I’m interested in'} <span>*</span><NativeSelect id="enquiry-interest" name="interest" required defaultValue=""><NativeSelectOption value="" disabled>Choose an option</NativeSelectOption>{options.map(item=><NativeSelectOption key={item} value={item}>{item}</NativeSelectOption>)}</NativeSelect></label></div><label htmlFor="enquiry-reference">{isTalent?'Portfolio / showreel link':'Website / reference link'}<Input id="enquiry-reference" name="reference" type="url" placeholder="https://" maxLength={400}/></label><label htmlFor="enquiry-brief">{isTalent?'Tell us about your experience':'Tell us about your project'} <span>*</span><Textarea id="enquiry-brief" name="brief" required minLength={15} maxLength={1800} rows={5} placeholder={isTalent?'Your experience, interests, and availability…':'Your idea, goals, preferred timeline, and what support you need…'}/></label><div className="form-bottom"><p>Only share information you want the ProDyum team to receive. Nothing is submitted until you send the email.</p><button className="primary-link" type="submit">Prepare email <ArrowUpRight size={18}/></button></div></form>{draft&&<section className="draft-panel" aria-label="Your prepared enquiry"><h3><Check size={18}/> Your email is ready to review</h3><p role="status">It has not been sent. Open your email app to send it, or copy the message.</p><pre tabIndex={0}>{draft.body}</pre><div className="draft-actions"><a className="primary-link" href={draft.href}><Mail size={16}/> Open email app</a><button className="text-action" onClick={async()=>{try{await navigator.clipboard.writeText(draft.body);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}}><Copy size={16}/>{copied?'Copied':'Copy message'}</button></div>{copyError&&<p role="alert">Copy isn’t available here. Select the message above and copy it manually.</p>}</section>}</div>;
}
