'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowUpRight, Menu } from 'lucide-react';

export function SiteHeader(){
 const path=usePathname();const division=path?.startsWith('/entertainment')?'entertainment':path?.startsWith('/it')?'it':'brand';
 const links=division==='it'?[['Digital','/it'],['Services','/it/services'],['Projects','/it/portfolio'],['About','/it/about'],['Careers','/it/careers']]:division==='entertainment'?[['Studio','/entertainment'],['Services','/entertainment/services'],['Projects','/entertainment/projects'],['Partners','/entertainment/investors'],['Cast & crew','/entertainment/casting']]:[['Digital','/it'],['Entertainment','/entertainment'],['About us','/about']];
 const contact=division==='brand'?'/contact':`/${division}/contact`;
 return <><a className="skip-link" href="#main-content">Skip to content</a><header className={`site-header replacement-header ${division}`}><Link className="wordmark" href="/" aria-label="ProDyum home">prodyum<span>✳</span></Link>{division!=='brand'&&<Link className="division-label" href={`/${division}`}>{division==='it'?'IT PVT LTD':'ENTERTAINMENTS'}</Link>}<nav className="desktop-navigation" aria-label="Main navigation">{links.map(([name,href])=><Link key={href} href={href} aria-current={path===href?'page':undefined}>{name}</Link>)}<Link className="nav-contact" href={contact}>Let’s talk <ArrowUpRight size={16}/></Link></nav><details className="mobile-navigation" key={path}><summary aria-label="Open navigation"><Menu size={24}/></summary><nav aria-label="Mobile navigation">{links.map(([name,href])=><Link key={href} href={href} aria-current={path===href?'page':undefined}>{name}</Link>)}<Link href={contact}>Let’s talk <ArrowUpRight size={16}/></Link><Link href={division==='it'?'/entertainment':'/it'}>{division==='it'?'Explore Entertainment':'Explore Digital'} <ArrowUpRight size={16}/></Link></nav></details></header></>;
}
export function SiteFooter(){return <footer className="site-footer"><div className="footer-top"><Link className="wordmark" href="/">prodyum<span>✳</span></Link><p>Technology. Creativity. Cinema.<br/>Made in Hyderabad.</p><Link className="footer-cta" href="/contact">Let’s make it happen <ArrowUpRight size={22}/></Link></div><div className="footer-columns"><div><h2>Our worlds</h2><Link href="/it">ProDyum IT</Link><Link href="/entertainment">ProDyum Entertainments</Link><Link href="/about">About ProDyum</Link></div><div><h2>Digital</h2><Link href="/it/services">Services</Link><Link href="/it/portfolio">Project enquiries</Link><Link href="/it/careers">Careers</Link></div><div><h2>Cinema</h2><Link href="/entertainment/projects">Channels & content</Link><Link href="/entertainment/services">Production services</Link><Link href="/entertainment/investors">Partnerships</Link><Link href="/entertainment/casting">Casting & crew</Link></div><div><h2>Start a conversation</h2><Link href="/contact">Contact us</Link><a href="mailto:hr@prodyum.in">hr@prodyum.in</a><a href="https://www.youtube.com/@ProDyumEntertainments" target="_blank" rel="noopener noreferrer">YouTube <ArrowUpRight size={14}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} ProDyum. All rights reserved.</span><span>HYDERABAD, TELANGANA, INDIA</span></div></footer>}
